# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Kristi Nikolla
tagline:          ''
description:      ''
url:              https://knikolla.github.io
baseurl:          https://knikolla.github.io

author:
  name:           'Kristi Nikolla'
  url:            https://knikolla.github.io

gems: [jekyll-paginate, jekyll-gist]
paginate:         10
paginate_path: "page:num"
excerpt_separator: <!--more-->

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/knikolla/knikolla.github.io
