# Dependencies
highlighter:      rb-pygments

# Permalinks
permalink:        pretty

# Setup
title:            Kristi Nikolla
tagline:          ''
description:      ''
url:              http://knikolla.github.io
baseurl:          /

author:
  name:           'Kristi Nikolla'
  url:            http://knikolla.github.io

gems: [jekyll-paginate, jekyll-gist]
paginate:         5
paginate_path: "page:num"
excerpt_separator: <!--more-->

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/knikolla/knikolla.github.io
