# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            knikolla
tagline:          'Kristi Nikolla'
description:      ''
url:              http://knikolla.github.io
baseurl:          /

author:
  name:           'Kristi Nikolla'
  url:            http://knikolla.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/knikolla/knikolla.github.io
